//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Mse.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Mse.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Managed Stack Explorer.
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently being logged.
        /// </summary>
        internal static string BeingLoggedToolTip {
            get {
                return ResourceManager.GetString("BeingLoggedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string collapseDataViewButtonCollapse {
            get {
                return ResourceManager.GetString("collapseDataViewButtonCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string collapseDataViewButtonExpand {
            get {
                return ResourceManager.GetString("collapseDataViewButtonExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid combination of arguments.
        /// </summary>
        internal static string combinationArgsError {
            get {
                return ResourceManager.GetString("combinationArgsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Time.
        /// </summary>
        internal static string cpuTime {
            get {
                return ResourceManager.GetString("cpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string cpuUsage {
            get {
                return ResourceManager.GetString("cpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack depth must be 0 or greater.
        /// </summary>
        internal static string depthError {
            get {
                return ResourceManager.GetString("depthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string descriptionWord {
            get {
                return ResourceManager.GetString("descriptionWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must be one second or greater.
        /// </summary>
        internal static string durationsError {
            get {
                return ResourceManager.GetString("durationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string findBoxCaption {
            get {
                return ResourceManager.GetString("findBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished searching stack.
        /// </summary>
        internal static string findBoxFinished {
            get {
                return ResourceManager.GetString("findBoxFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormRun {
            get {
                object obj = ResourceManager.GetObject("FormRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string forWord {
            get {
                return ResourceManager.GetString("forWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen 0 Collections.
        /// </summary>
        internal static string gen0Coll {
            get {
                return ResourceManager.GetString("gen0Coll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen 1 Collections.
        /// </summary>
        internal static string gen1Coll {
            get {
                return ResourceManager.GetString("gen1Coll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen 2 Collections.
        /// </summary>
        internal static string gen2Coll {
            get {
                return ResourceManager.GetString("gen2Coll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be one second or greater.
        /// </summary>
        internal static string intervalTimeError {
            get {
                return ResourceManager.GetString("intervalTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments.
        /// </summary>
        internal static string invalidArgsError {
            get {
                return ResourceManager.GetString("invalidArgsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time intervals.
        /// </summary>
        internal static string invalidIntervalError {
            get {
                return ResourceManager.GetString("invalidIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The path &quot;{1}&quot; is invalid..
        /// </summary>
        internal static string invalidOutFileName {
            get {
                return ResourceManager.GetString("invalidOutFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid process or thread id.
        /// </summary>
        internal static string invalidProcOrThread {
            get {
                return ResourceManager.GetString("invalidProcOrThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill command cannot be combined with other operations.
        /// </summary>
        internal static string killError {
            get {
                return ResourceManager.GetString("killError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot kill a process with id.
        /// </summary>
        internal static string killIdError {
            get {
                return ResourceManager.GetString("killIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging every.
        /// </summary>
        internal static string logEveryWord {
            get {
                return ResourceManager.GetString("logEveryWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack logging rate must be.
        /// </summary>
        internal static string logRateError {
            get {
                return ResourceManager.GetString("logRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Heap.
        /// </summary>
        internal static string managedHeap {
            get {
                return ResourceManager.GetString("managedHeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Processes.
        /// </summary>
        internal static string ManagedProcesses {
            get {
                return ResourceManager.GetString("ManagedProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds or greater.
        /// </summary>
        internal static string milliOrGreater {
            get {
                return ResourceManager.GetString("milliOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More arguments expected.
        /// </summary>
        internal static string moreArgsExpectedError {
            get {
                return ResourceManager.GetString("moreArgsExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) Microsoft Corporation. All rights reserved..
        /// </summary>
        internal static string mseCopyright {
            get {
                return ResourceManager.GetString("mseCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Stack Explorer (MSE) is a lightweight tool that provides a quick and easy way to monitor .NET 2.0 managed processes and their stacks. The ability to view a program’s stack and how it changes over time is an important method in determining reasons for possible errors.  MSE provides a simple interface to allow you to monitor multiple processes at once and build periodic stack log files. MSE works by quickly attaching to a process when a stack trace is requested, then detaching the moment the stack tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mseDescription {
            get {
                return ResourceManager.GetString("mseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Stack Explorer.
        /// </summary>
        internal static string MSEfull {
            get {
                return ResourceManager.GetString("MSEfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft (R) Managed Stack Explorer 2005..
        /// </summary>
        internal static string mseTitleString {
            get {
                return ResourceManager.GetString("mseTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoAction {
            get {
                object obj = ResourceManager.GetObject("NoAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        internal static string numberFormatError {
            get {
                return ResourceManager.GetString("numberFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Access to the path &quot;{1}&quot; is denied..
        /// </summary>
        internal static string outFileAccessDenied {
            get {
                return ResourceManager.GetString("outFileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional parameter expected for.
        /// </summary>
        internal static string parameterExpectedError {
            get {
                return ResourceManager.GetString("parameterExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Memory.
        /// </summary>
        internal static string physicalMem {
            get {
                return ResourceManager.GetString("physicalMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string processCompany {
            get {
                return ResourceManager.GetString("processCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string processDescription {
            get {
                return ResourceManager.GetString("processDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid process id.
        /// </summary>
        internal static string processIdError {
            get {
                return ResourceManager.GetString("processIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Info for.
        /// </summary>
        internal static string processInfoFor {
            get {
                return ResourceManager.GetString("processInfoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string processName {
            get {
                return ResourceManager.GetString("processName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process list refresh rate must be.
        /// </summary>
        internal static string processRefreshRateError {
            get {
                return ResourceManager.GetString("processRefreshRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshDocView {
            get {
                object obj = ResourceManager.GetObject("RefreshDocView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same command appears twice.
        /// </summary>
        internal static string repeatedCommandError {
            get {
                return ResourceManager.GetString("repeatedCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes to the settings?.
        /// </summary>
        internal static string saveSettings {
            get {
                return ResourceManager.GetString("saveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string secondsWord {
            get {
                return ResourceManager.GetString("secondsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowAllComments {
            get {
                object obj = ResourceManager.GetObject("ShowAllComments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Unavailable.
        /// </summary>
        internal static string sourceUnavailable {
            get {
                return ResourceManager.GetString("sourceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace depth is set to show all frames.
        /// </summary>
        internal static string stackDepthAll {
            get {
                return ResourceManager.GetString("stackDepthAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace depth is.
        /// </summary>
        internal static string StackDepthIs {
            get {
                return ResourceManager.GetString("StackDepthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace refresh rate must be.
        /// </summary>
        internal static string stackRefreshRateError {
            get {
                return ResourceManager.GetString("stackRefreshRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace for.
        /// </summary>
        internal static string stackTraceFor {
            get {
                return ResourceManager.GetString("stackTraceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Stack Logging.
        /// </summary>
        internal static string StartLogging {
            get {
                return ResourceManager.GetString("StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Stack Logging.
        /// </summary>
        internal static string StopLogging {
            get {
                return ResourceManager.GetString("StopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread refresh rate must be.
        /// </summary>
        internal static string threadRefreshRateError {
            get {
                return ResourceManager.GetString("threadRefreshRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads of.
        /// </summary>
        internal static string threadsOf {
            get {
                return ResourceManager.GetString("threadsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        internal static string threadWord {
            get {
                return ResourceManager.GetString("threadWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Time in GC.
        /// </summary>
        internal static string timeInGC {
            get {
                return ResourceManager.GetString("timeInGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Argument.
        /// </summary>
        internal static string unknownArgError {
            get {
                return ResourceManager.GetString("unknownArgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///{0} [process options] [thread options] [logging]
        ///
        ///Process options:
        ///
        ////p(rocess) [process id,...]    Display list of managed processes.
        ////i(nfo)                        Display info about the specified process(es).
        ////k(ill)                        Kill the process(es) specified by /p.
        ////s(tack)                       Display stack traces of all threads.
        ////dep(th) &lt;depth&gt;               Number of stack frames to be shown when 
        ///                                   using /s. Default is to show all.
        ///
        ///Thr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usageString {
            get {
                return ResourceManager.GetString("usageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Memory.
        /// </summary>
        internal static string virtualMem {
            get {
                return ResourceManager.GetString("virtualMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame.
        /// </summary>
        internal static string wordFrame {
            get {
                return ResourceManager.GetString("wordFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frames.
        /// </summary>
        internal static string wordFrames {
            get {
                return ResourceManager.GetString("wordFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string wordID {
            get {
                return ResourceManager.GetString("wordID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        internal static string wordThread {
            get {
                return ResourceManager.GetString("wordThread", resourceCulture);
            }
        }
    }
}
